INSERT INTO PERSON(FIRST_NAME, LAST_NAME,EMAIL,PHONE) VALUES ('taha1', 'TURGUT','taha@gmail','0493000000');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME,EMAIL,PHONE) VALUES ('taha2', 'TURGUT','taha@gmail','0493000000');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME,EMAIL,PHONE) VALUES ('taha3', 'TURGUT','taha@gmail','0493000000');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME,EMAIL,PHONE) VALUES ('taha4', 'TURGUT','taha@gmail','0493000000');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME,EMAIL,PHONE) VALUES ('taha5', 'TURGUT','taha@gmail','0493000000');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME,EMAIL,PHONE) VALUES ('taha6', 'TURGUT','taha@gmail','0493000000');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME,EMAIL,PHONE) VALUES ('taha7', 'TURGUT','taha@gmail','0493000000');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME,EMAIL,PHONE) VALUES ('taha8', 'TURGUT','taha@gmail','0493000000');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME,EMAIL,PHONE) VALUES ('taha9', 'TURGUT','taha@gmail','0493000000');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME,EMAIL,PHONE) VALUES ('taha10', 'TURGUT','taha@gmail','0493000000');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME,EMAIL,PHONE) VALUES ('taha11', 'TURGUT','taha@gmail','0493000000');

INSERT INTO COURSE(NAME,DESCRIPTION,STUDY_POINTS) VALUES ( 'testCourseName1','testCourseDescription1',15 );

INSERT INTO SESSION(START_Date_Time,END_Date_Time,COURSE_ID) VALUES ( '2020-01-01','2021-06-06',1);

INSERT INTO PERSON_COURSE(COURSE_ID,PERSON_ID) VALUES ( 1,1 );
INSERT INTO PERSON_COURSE(COURSE_ID,PERSON_ID) VALUES ( 1,2 );
INSERT INTO PERSON_COURSE(COURSE_ID,PERSON_ID) VALUES ( 1,3 )
